{{- if not .Values.backend.falkordb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sibyl.fullname" . }}-falkordb
  labels:
    {{- include "sibyl.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.falkordb.password }}
  password: {{ .Values.backend.falkordb.password | b64enc | quote }}
  {{- else }}
  # Auto-generate password if not provided
  password: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}
